### ISSUE TITLE
Filtering Contacts?

### ISSUE THREAD

**Issue by JacksonRiso** [phusion/frontapp#13]
Hey there!

Love what you have created. 

Question: Is there a way to filter contacts? E.g. I want to find all contacts NOT in a group, or where a specific field is empty. 

Cheers!

**Comment by scarhand** [comment]
I don't think there is. The only search parameters supported for listing contacts are updated_before and updated_after (see: https://dev.frontapp.com/reference/contacts#search-parameters).

It's been a long time since I looked at this, I'm right now not even sure if the q-parameter is supported for contacts :)

**Comment by JacksonRiso** [comment]
Thank you!
